<a href="https://colab.research.google.com/github/Antelope10/Antelope10/blob/main/tf_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

data = pd.read_csv('sample_data/mnist_train_small.csv')
data.head()
data = np.array(data)
m,n = data.shape

Y_train = np.zeros((m,10))
X_train = data[:,1:n]

for i in range(m):
  Y_train[i,data[i,0]] = 1



array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [68]:
model = keras.Sequential(
    [
        layers.Dense(784,activation="relu", name="layer1"),
        layers.Dense(3,activation="relu", name="layer2"),
        layers.Dense(10,name="layer3"),
    ]
)

model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics='accuracy')
model.fit(X_train,Y_train,batch_size=32,epochs=5)

Epoch 1/5
625/625 [==============================] - 4s 5ms/step - loss: 9.9138 - accuracy: 0.1124
Epoch 2/5
625/625 [==============================] - 3s 5ms/step - loss: 9.9542 - accuracy: 0.1122
Epoch 3/5
625/625 [==============================] - 3s 5ms/step - loss: 9.9542 - accuracy: 0.1122
Epoch 4/5
625/625 [==============================] - 3s 5ms/step - loss: 9.9542 - accuracy: 0.1122
Epoch 5/5
625/625 [==============================] - 3s 5ms/step - loss: 9.9542 - accuracy: 0.1122


In [63]:
model(X_train)

<tf.Tensor: shape=(19999, 10), dtype=float32, numpy=
array([[-197.85081 , -125.26632 , -309.67996 , ..., -264.74408 ,
         195.30087 ,  171.93585 ],
       [-204.00876 ,  -60.015316, -240.05255 , ..., -374.04037 ,
         251.70522 ,  228.04407 ],
       [-280.58395 , -110.50394 , -373.81573 , ..., -363.49948 ,
         302.15186 ,  329.42938 ],
       ...,
       [-260.24878 , -147.81277 , -413.05508 , ..., -511.1638  ,
         259.89194 ,  309.14642 ],
       [-191.82123 , -210.08476 , -319.98047 , ..., -441.24872 ,
         208.1753  ,  239.66689 ],
       [-331.5595  , -212.70709 , -419.13174 , ..., -258.59222 ,
         280.1582  ,  154.69363 ]], dtype=float32)>